/* englisch.js — die Sprachfassung für den Film.
 *
 * Warum eine Schicht und keine Übersetzung im Entwurf: Velum ist auf Deutsch
 * gedacht. Die Belegbindung, die Abnahmeberichte, jeder Schirmname — alles
 * hängt daran. Ein Film für Instagram hängt daran nicht; er braucht Englisch.
 * Also wird nicht der Entwurf umgeschrieben, sondern für die Dauer der
 * Aufnahme ein Wörterbuch über ihn gelegt.
 *
 * Der Schlüssel ist der TEXTKNOTEN, nicht das Wort. Wortweises Ersetzen
 * erzeugt Sätze, die kein Mensch geschrieben hat („Die Woche was voll") —
 * genau das, was der Auftrag ausschließt. Darum steht hier jeder sichtbare
 * Textknoten der gefilmten Schirme einzeln, mit seiner englischen Fassung.
 *
 * Gelesen wird normalisiert: weiche Trennstriche (U+00AD), geschützte
 * Leerzeichen und Mehrfachleerzeichen fallen vor dem Nachschlagen weg. In der
 * Bibliothek stehen die Titel mit Trennhilfen im Text („Zell­biologie"); ohne
 * die Normalisierung träfe kein einziger Schlüssel.
 */
(function (global) {
  'use strict';

  /* [deutsch, englisch] — Reihenfolge wie im Schirm, damit man beim
     Nachlesen mitgeht statt zu suchen. */
  var PAARE = [

    /* ── Seitenleiste, überall gleich ─────────────────────────────── */
    ['Heute', 'Today'],
    ['Bibliothek', 'Library'],
    ['Eingang', 'Inbox'],
    ['Module', 'Courses'],
    ['Notizen', 'Notes'],
    ['Aufgaben', 'Tasks'],
    ['Lernkarten', 'Flashcards'],
    ['Semester', 'Semester'],
    ['Biologie', 'Biology'],
    ['Analysis II', 'Calculus II'],
    ['Einstellungen', 'Settings'],
    ['Neu', 'New'],
    ['Suchen', 'Search'],

    /* ── Heute ────────────────────────────────────────────────────── */
    ['Guten Morgen, Emil', 'Good morning, Mara'],
    ['Donnerstag, 13. November.', 'Thursday, 13 November.'],
    ['Sechs Aufgaben', 'Six tasks'],
    ['sind heute fällig, davon eine mit Deadline.', 'are due today, one with a hard deadline.'],
    ['23 Lernkarten', '23 flashcards'],
    ['warten — 8 davon aus der Vorlesung von gestern.', 'are waiting — 8 of them from yesterday’s lecture.'],
    ['Aus deiner Vorlesung von gestern', 'From yesterday’s lecture'],
    ['Kette', 'Chain'],
    ['Notiz', 'Note'],
    ['Zellbiologie', 'Cell Biology'],
    ['14 Absätze · 16:20 Uhr', '14 paragraphs · 16:20'],
    ['Wurde zu', 'Became'],
    ['12 Karten', '12 cards'],
    ['Deck „Zellbiologie"', '“Cell Biology” deck'],
    ['Deck „Zellbiologie“', '“Cell Biology” deck'],
    ['Heute fällig', 'Due today'],
    ['8 Karten', '8 cards'],
    ['ca. 4 Minuten', 'about 4 minutes'],
    ['Lernen', 'Study'],
    ['WEITERMACHEN', 'PICK UP WHERE YOU LEFT OFF'],
    ['Canvas · vor 18 Minuten', 'Canvas · 18 minutes ago'],
    ['Analysis II — Übungsblatt 5', 'Calculus II — Problem Set 5'],
    ['Grenzwertsätze, Aufgabe 3 halb gelöst', 'Limit theorems, problem 3 half solved'],
    ['Journal · gestern 22:10', 'Journal · yesterday 22:10'],
    ['Entwurf ohne Titel', 'Untitled draft'],
    ['„Die Woche war voll, aber die Laborgruppe…"', '“It was a full week, but the lab group…”'],
    ['„Die Woche war voll, aber die Laborgruppe…“', '“It was a full week, but the lab group…”'],
    ['Weiterschreiben', 'Keep writing'],
    ['HEUTE FÄLLIG', 'DUE TODAY'],
    ['Statistik-Blatt 4 abgeben', 'Hand in statistics sheet 4'],
    ['Heute 18:00', 'Today 18:00'],
    ['Laborprotokoll Zellkultur schreiben', 'Write up the cell culture lab report'],
    ['aus „Zellbiologie"', 'from “Cell Biology”'],
    ['aus „Zellbiologie“', 'from “Cell Biology”'],
    ['Rückmeldung an Prof. Wendt', 'Reply to Prof. Wendt'],
    ['Uni · 2 Teilschritte', 'University · 2 steps'],
    ['Bücher in der Bibliothek verlängern', 'Renew the library books'],
    ['Persönlich', 'Personal'],
    ['Karteikarten Anatomie nacharbeiten', 'Catch up on anatomy flashcards'],
    ['Biologie · wiederholt sich wöchentlich', 'Biology · repeats weekly'],
    ['Abend', 'Evening'],
    ['HEUTE IN ZAHLEN', 'TODAY IN NUMBERS'],
    ['Aufgaben fällig', 'tasks due'],
    ['Karten zu lernen', 'cards to review'],
    ['Journal-Entwurf offen', 'journal draft open'],
    ['Tage in Folge', 'day streak'],
    ['Lücke = ausgelassen · Ring = heute', 'gap = skipped · ring = today'],
    ['IMPULS', 'PROMPT'],
    ['Was hat dich heute länger beschäftigt, als du erwartet hättest?',
     'What kept you thinking longer today than you expected?'],
    ['Eintrag beginnen', 'Start an entry'],
    ['Vor einem Jahr', 'One year ago'],
    ['Erster Tag im Labor', 'First day in the lab'],
    ['„Ich habe drei Stunden gebraucht, um die Pipette richtig zu halten."',
     '“It took me three hours just to hold the pipette properly.”'],
    ['„Ich habe drei Stunden gebraucht, um die Pipette richtig zu halten.“',
     '“It took me three hours just to hold the pipette properly.”'],

    /* ── Notizen (Liste) ──────────────────────────────────────────── */
    ['In 42 Notizen suchen', 'Search 42 notes'],
    ['Neue Notiz', 'New note'],
    ['Alle Notizen', 'All notes'],
    ['Angeheftet', 'Pinned'],
    ['Papierkorb', 'Trash'],
    ['#uni', '#uni'],
    ['/bio', '/bio'],
    ['/mathe', '/math'],
    ['#labor', '#lab'],
    ['#prüfung', '#exam'],
    ['Notizbücher', 'Notebooks'],
    ['Laborjournal', 'Lab Journal'],
    ['Semesterplanung', 'Semester Plan'],
    ['Lesenotizen Soziologie', 'Sociology Reading Notes'],
    ['4 Notizen ohne Tag', '4 notes without a tag'],
    ['Tag hinzufügen', 'Add tag'],
    ['Alle', 'All'],
    ['Mit Aufgaben', 'With tasks'],
    ['Mit Karten', 'With cards'],
    ['Verweise', 'Links'],
    ['Geändert', 'Modified'],
    ['ANGEHEFTET', 'PINNED'],
    ['Zellbiologie — Vorlesung 9', 'Cell Biology — Lecture 9'],
    ['gestern 16:20', 'yesterday 16:20'],
    ['Mitochondrium: Doppelmembran, eigene Ribosomen, teilt sich selbst. Der Golgi-Apparat verpackt, was das Endoplasmatische Retikulum vorbereitet hat.',
     'Mitochondrion: double membrane, its own ribosomes, divides by itself. The Golgi apparatus packages whatever the endoplasmic reticulum has prepared.'],
    ['1 Aufgabe', '1 task'],
    ['Semesterplanung Wintersemester', 'Winter semester planning'],
    ['2. Nov', 'Nov 2'],
    ['Analysis II liegt Dienstag und Donnerstag, das Labor blockt den Mittwochnachmittag. Die Prüfungswoche beginnt am 9. Februar — davor drei freie Wochen.',
     'Calculus II sits on Tuesday and Thursday, the lab blocks Wednesday afternoon. Exam week starts on 9 February — three clear weeks before it.'],
    ['DIESE WOCHE', 'THIS WEEK'],
    ['Osmose und Zellmembran', 'Osmosis and the cell membrane'],
    ['Di 11. Nov', 'Tue 11 Nov'],
    ['Wasser wandert dorthin, wo mehr gelöst ist. Versuch mit Kartoffelstäbchen: nach 40 Minuten 3 mm kürzer, in der Salzlösung deutlich weicher.',
     'Water moves to where more is dissolved. Potato stick experiment: 3 mm shorter after 40 minutes, and noticeably softer in the salt solution.'],
    ['Laborjournal — Zellkultur, Tag 3', 'Lab Journal — cell culture, day 3'],
    ['Mo 10. Nov', 'Mon 10 Nov'],
    ['Passage 4, Konfluenz bei 80 %. Jana hat das Medium um 9:15 gewechselt, Milan zählt morgen früh aus. Das Foto vom Inkubator liegt dabei.',
     'Passage 4, confluence at 80 %. Jana changed the medium at 9:15, Milan counts tomorrow morning. The incubator photo is attached.'],
    ['2 Fotos', '2 photos'],
    ['aus', 'from'],
    ['Aufgabe', 'Task'],
    ['Analysis II — Grenzwertsätze', 'Calculus II — limit theorems'],
    ['Satz von Bolzano-Weierstraß mit den drei Beispielen von Prof. Wendt. Aufgabe 3 auf Blatt 5 hängt direkt daran, Abgabe ist heute um 18:00.',
     'Bolzano–Weierstrass with the three examples from Prof. Wendt. Problem 3 on sheet 5 hangs directly off it, due today at 18:00.'],
    ['Lesenotizen Soziologie — Kapitel 2', 'Sociology Reading Notes — chapter 2'],
    ['Fr 7. Nov', 'Fri 7 Nov'],
    ['Bourdieu, Formen des Kapitals. Die Stelle auf Seite 187 will ich im Seminar zitieren — soziales Kapital ist vor allem Netzwerkarbeit.',
     'Bourdieu, forms of capital. I want to quote page 187 in the seminar — social capital is mostly network labour.'],
    ['4 Zitate', '4 quotes'],

    /* ── Notiz (Editor) ───────────────────────────────────────────── */
    ['Biologie · Semester 3', 'Biology · Term 3'],
    ['Vorlesung 6 · Prof. Wendt', 'Lecture 6 · Prof. Wendt'],
    ['Tag', 'Tag'],
    ['Zuletzt bearbeitet gestern 16:20 ·', 'Last edited yesterday 16:20 ·'],
    ['14 Absätze', '14 paragraphs'],
    ['Membran und Transport', 'Membrane and transport'],
    ['Die Zellmembran ist', 'The cell membrane is'],
    ['selektiv permeabel', 'selectively permeable'],
    [': kleine unpolare Moleküle passieren frei, Ionen brauchen Kanäle. Für Wasser gilt der Sonderfall',
     ': small non-polar molecules pass freely, ions need channels. Water is the special case —'],
    ['Osmose', 'Osmosis'],
    ['NEUE KARTE', 'NEW CARD'],
    ['Osmose ist die Diffusion von Wasser durch eine ▮ Membran.',
     'Osmosis is the diffusion of water through a ▮ membrane.'],
    ['Lückentext-Karte', 'Cloze card'],
    ['Frage/Antwort', 'Q & A'],
    ['Merksatz:', 'Key sentence:'],
    ['Osmose ist die Diffusion von Wasser durch eine semipermeable Membran.',
     'Osmosis is the diffusion of water through a semipermeable membrane.'],
    ['Abbildung 4.2 aus der Vorlesung ergänzen', 'Add figure 4.2 from the lecture'],
    ['Jana nach dem Messprotokoll vom Dienstag fragen', 'Ask Jana for Tuesday’s measurement log'],
    ['MERKEN', 'REMEMBER'],
    ['Wasser wandert dorthin, wo die Teilchenkonzentration höher ist.',
     'Water moves towards the higher particle concentration.'],
    ['„Die Zelle ist die kleinste Einheit, die alle Merkmale des Lebendigen erfüllt."',
     '“The cell is the smallest unit that meets every criterion of life.”'],
    ['„Die Zelle ist die kleinste Einheit, die alle Merkmale des Lebendigen erfüllt.“',
     '“The cell is the smallest unit that meets every criterion of life.”'],
    ['Vorlesung 6, Prof. Wendt', 'Lecture 6, Prof. Wendt'],
    ['# Zellen pro mL — Neubauer, Verdünnung 1:2', '# cells per mL — Neubauer, dilution 1:2'],
    ['ORGANELL', 'ORGANELLE'],
    ['AUFGABE', 'FUNCTION'],
    ['Mitochondrium', 'Mitochondrion'],
    ['Energie als ATP', 'Energy as ATP'],
    ['Golgi-Apparat', 'Golgi apparatus'],
    ['Sortieren und Verpacken', 'Sorting and packaging'],
    ['Endoplasmatisches Retikulum', 'Endoplasmic reticulum'],
    ['Synthese und Transport', 'Synthesis and transport'],
    ['Organellen im Überblick', 'Organelles at a glance'],
    ['Blöcke ausgeblendet', 'blocks hidden'],
    ['BLOCK', 'BLOCK'],
    ['Alles gesichert · 9:39', 'All saved · 9:39'],
    ['für Blöcke', 'for blocks'],
    ['Übersicht', 'Outline'],
    ['Verlauf', 'History'],
    ['INHALT', 'CONTENTS'],
    ['Aufbau der Zelle', 'Structure of the cell'],
    ['Fragen an Prof. Wendt', 'Questions for Prof. Wendt'],
    ['BACKLINKS', 'BACKLINKS'],
    ['Laborjournal · 12. Nov', 'Lab Journal · 12 Nov'],
    ['DARAUS ENTSTANDEN', 'WHAT CAME OF IT'],
    ['Karten', 'cards'],
    ['heute fällig', 'due today'],
    ['Laborprotokoll Zellkultur', 'Cell culture lab report'],
    ['VERWANDTE NOTIZEN', 'RELATED NOTES'],
    ['Zellmembran', 'Cell membrane'],
    ['AM SEITENRAND', 'IN THE MARGIN'],
    ['verlinkt', 'linked'],
    ['erwähnt, noch nicht verlinkt', 'mentioned, not yet linked'],
    ['STATISTIK', 'STATISTICS'],
    ['Wörter', 'words'],
    ['Min. lesen', 'min read'],
    ['Absätze', 'paragraphs'],
    ['Links', 'links'],

    /* ── Bibliothek ───────────────────────────────────────────────── */
    ['Raster', 'Grid'],
    ['Liste', 'List'],
    ['Zuletzt geändert', 'Last modified'],
    ['SMART-ORDNER', 'SMART FOLDERS'],
    ['Sichten, keine Schubladen', 'Views, not drawers'],
    ['Diese Woche', 'This week'],
    ['seit Montag', 'since Monday'],
    ['Markiert', 'Starred'],
    ['mit Stern', 'with a star'],
    ['Mit Audio', 'With audio'],
    ['mit Aufnahme', 'with a recording'],
    ['Prüfung Februar', 'Feb exam'],
    ['aus dem Graphen', 'from the graph'],
    ['ALLE NOTIZBÜCHER', 'ALL NOTEBOOKS'],
    ['Nach Änderung sortiert', 'Sorted by date modified'],
    ['34 Seiten', '34 pages'],
    ['heute', 'today'],
    ['18 Seiten', '18 pages'],
    ['gestern', 'Wed'],
    ['Genetik II', 'Genetics II'],
    ['41 Seiten', '41 pages'],
    ['Wendt · Vorlesung', 'Wendt · Lecture'],
    ['56 Seiten', '56 pages'],
    ['Di.', 'Tue'],
    ['Praktikum Zellkultur', 'Cell Culture Lab'],
    ['24 Seiten', '24 pages'],
    ['9 Seiten', '9 pages'],
    ['Mo.', 'Mon'],
    ['Prüfungsfragen', 'Exam Questions'],
    ['22 Seiten', '22 pages'],
    ['Statistik', 'Statistics'],
    ['12 Seiten', '12 pages'],
    ['7.11.', 'Nov 7'],
    ['Zitate', 'Quotes'],
    ['7 Seiten', '7 pages'],
    ['4.11.', 'Nov 4'],
    ['Exkursion Harz', 'Field Trip Harz'],
    ['11 Seiten', '11 pages'],
    ['2.11.', 'Nov 2'],
    ['Messreihen', 'Measurements'],
    ['15 Seiten', '15 pages'],
    ['31.10.', 'Oct 31'],
    ['wird geladen', 'loading'],
    ['Klausur Februar', 'February Exam'],
    ['62 % · aus iCloud', '62 % · from iCloud'],
    ['Diagramme', 'Diagrams'],
    ['8 Seiten', '8 pages'],
    ['29.10.', 'Oct 29'],
    ['52 Seiten', '52 pages'],
    ['28.10.', 'Oct 28'],
    ['26 Seiten', '26 pages'],
    ['27.10.', 'Oct 27'],
    ['Fragen an Wendt', 'Questions for Wendt'],
    ['3 Seiten', '3 pages'],
    ['26.10.', 'Oct 26'],
    ['Protokolle', 'Protocols'],
    ['19 Seiten', '19 pages'],
    ['24.10.', 'Oct 24'],
    ['Skizzen Mikroskop', 'Microscope Sketches'],
    ['6 Seiten', '6 pages'],
    ['21.10.', 'Oct 21'],
    ['Umbenennen', 'Rename'],
    ['Duplizieren', 'Duplicate'],
    ['Verschieben', 'Move'],
    ['Zu Favoriten', 'Add to favourites'],
    ['Löschen', 'Delete'],

    /* ── Aufgaben ─────────────────────────────────────────────────── */
    ['Heute · 13. November', 'Today · 13 November'],
    ['Planer', 'Planner'],
    ['Matrix', 'Matrix'],
    ['Board', 'Board'],
    ['Kalender', 'Calendar'],
    ['Bereich', 'Area'],
    ['Laborprotokoll', 'Lab report'],
    ['morgen 14 Uhr', 'tomorrow 2pm'],
    ['Sichern', 'Save'],
    ['ERKANNT', 'PICKED UP'],
    ['Morgen 14:00', 'Tomorrow 14:00'],
    ['Hohe Priorität', 'High priority'],
    ['Bereich Biologie', 'Area Biology'],
    ['Antippen zum Ändern', 'Tap to change'],
    ['Aufgaben ·', 'tasks ·'],
    ['erledigt', 'done'],
    ['Messwerte von Tag 3 eintragen', 'Enter the day 3 readings'],
    ['Geplant 14:00', 'Scheduled 14:00'],
    ['wenn das Deck', 'when the deck'],
    ['fällig ist', 'comes due'],
    ['Planen', 'Schedule'],
    ['Übungen 12. Nov.', 'Problem set 12 Nov'],
    ['Übungsblatt 5 fertig rechnen', 'Finish problem set 5'],
    ['Geplant morgen', 'Scheduled tomorrow'],
    ['Quelle im Papierkorb', 'Source in trash'],
    ['Geplant 16:00', 'Scheduled 16:00'],
    ['noch 0 Tage', 'due today'],
    ['Uni', 'University'],
    ['von', 'of'],
    ['Schritten', 'steps'],
    ['Termin mit Wendt abgestimmt', 'Slot agreed with Wendt'],
    ['Jana und Milan zusagen', 'Confirm with Jana and Milan'],
    ['Heute erledigt', 'Done today'],
    ['Mo', 'Mon'],
    ['Di', 'Tue'],
    ['Mi', 'Wed'],
    ['Do', 'Thu'],
    ['Fr', 'Fri'],
    ['Sa', 'Sat'],
    ['So', 'Sun'],
    ['offen, davon', 'open,'],
    ['mit Frist.', 'with a deadline.'],
    ['EINGANG', 'INBOX'],
    ['ohne Bereich', 'without an area'],
    ['Jetzt sortieren', 'Sort now'],
    ['WOHER HEUTE KOMMT', 'WHERE TODAY CAME FROM'],
    ['Notiz ·', 'Note ·'],
    ['Canvas ·', 'Canvas ·'],
    ['heute ·', 'today ·'],
    ['ohne Herkunft', 'no origin'],
    ['Drei von sechs sind gestern in der Vorlesung entstanden.',
     'Three of six were created in yesterday’s lecture.'],

    /* ── Aufgabe (Detail) ─────────────────────────────────────────── */
    ['Heute · Donnerstag, 13. November', 'Today · Thursday, 13 November'],
    ['Heute 18:00 · noch 0 Tage', 'Today 18:00 · due today'],
    ['Uni · antippen klappt auf', 'University · tap to expand'],
    ['Labortermin für Jana und Milan bestätigen. Wendt hat Dienstag und Donnerstag angeboten.',
     'Confirm the lab slot for Jana and Milan. Wendt offered Tuesday and Thursday.'],
    ['Messreihe vom Dienstag auswerten. Bei Probe 3 weicht der Wert um 12 % ab — Vorlage liegt im „Laborjournal".',
     'Work through Tuesday’s measurement series. Sample 3 is off by 12 % — the template is in “Lab Journal”.'],
    ['Messreihe vom Dienstag auswerten. Bei Probe 3 weicht der Wert um 12 % ab — Vorlage liegt im „Laborjournal“.',
     'Work through Tuesday’s measurement series. Sample 3 is off by 12 % — the template is in “Lab Journal”.'],
    ['SCHRITTE', 'STEPS'],
    ['Diagramm im Canvas anlegen', 'Start the diagram in Canvas'],
    ['Abweichung bei', 'Note the deviation on'],
    ['Probe 3 notieren', 'sample 3'],
    ['Fazit und Literaturhinweis', 'Conclusion and reference'],
    ['Schritt hinzufügen', 'Add step'],
    ['Geplant', 'Scheduled'],
    ['Frist', 'Deadline'],
    ['Fr, 15. Nov', 'Fri 15 Nov'],
    ['noch 2 Tage', 'in 2 days'],
    ['Wiederholung', 'Repeat'],
    ['Keine', 'None'],
    ['Ort', 'Place'],
    ['Labor 3.14', 'Lab 3.14'],
    ['beim Ankommen', 'on arrival'],
    ['„Vor dem Fixieren jede Färbung fotografisch dokumentieren."',
     '“Photograph every stain before fixing.”'],
    ['„Vor dem Fixieren jede Färbung fotografisch dokumentieren.“',
     '“Photograph every stain before fixing.”'],
    ['diese Aufgabe', 'this task'],
    ['Zur Stelle', 'Jump to it'],
    ['Teilen', 'Share'],
    ['Bei der Bibliothek', 'At the library'],
    ['AKTIVITÄT', 'ACTIVITY'],
    ['Schritt wird gesichert', 'Saving step'],
    ['jetzt', 'now'],
    ['Schritt „Fazit" ergänzt', 'Added step “Conclusion”'],
    ['Schritt „Fazit“ ergänzt', 'Added step “Conclusion”'],
    ['Jana · gestern 18:05', 'Jana · yesterday 18:05'],
    ['Frist auf Fr, 15. Nov', 'Deadline set to Fri 15 Nov'],
    ['Emil · gestern 21:40', 'You · yesterday 21:40'],
    ['„Laborjournal" verknüpft', 'Linked “Lab Journal”'],
    ['„Laborjournal“ verknüpft', 'Linked “Lab Journal”'],
    ['Emil · Mi, 12. Nov 20:12', 'You · Wed 12 Nov 20:12'],
    ['Aus Absatz 7 erstellt', 'Created from paragraph 7'],
    ['aus „Zellbiologie" · Di, 11. Nov', 'from “Cell Biology” · Tue 11 Nov'],
    ['aus „Zellbiologie“ · Di, 11. Nov', 'from “Cell Biology” · Tue 11 Nov'],
    ['Ganzen Verlauf zeigen', 'Show full history'],
    ['VERKNÜPFT', 'LINKED'],
    ['Notiz · Quelle', 'Note · source'],
    ['Deck ·', 'Deck ·'],
    ['fällig', 'due'],
    ['Canvas · gestern', 'Canvas · yesterday'],
    ['Verknüpfung hinzufügen', 'Add a link'],
    ['GETEILT MIT', 'SHARED WITH'],
    ['Laborgruppe', 'Lab group'],
    ['Jana und Milan sehen diese Aufgabe, nicht das ganze Notizbuch.',
     'Jana and Milan see this task, not the whole notebook.'],

    /* ── Journal ──────────────────────────────────────────────────── */
    ['128 Einträge', '128 entries'],
    ['Timeline', 'Timeline'],
    ['Medien', 'Media'],
    ['Karte', 'Map'],
    ['Eintrag', 'Entry'],
    ['Nov.', 'Nov'],
    ['Donnerstag · 8:05', 'Thursday · 8:05'],
    ['Vor dem Praktikum', 'Before the lab'],
    ['Die Kultur von Dienstag sieht gut aus — die Dichte stimmt, nichts trüb. Jana meint, wir können die Passage heute schon ansetzen, wenn Milan das Medium rechtzeitig …',
     'Tuesday’s culture looks good — density is right, nothing cloudy. Jana thinks we can set up the passage today if Milan gets the medium in on time …'],
    ['Sprachnotiz wird übertragen', 'Transcribing voice note'],
    ['1:14 von 2:03', '1:14 of 2:03'],
    ['Stimmung 4', 'Mood 4'],
    ['Energie 3', 'Energy 3'],
    ['Labor 2', 'Lab 2'],
    ['Mittwoch · 22:10', 'Wednesday · 22:10'],
    ['Entwurf', 'Draft'],
    ['Ohne Titel', 'Untitled'],
    ['Die Woche war voll, aber die Laborgruppe hat mich getragen. Jana und Milan haben das Protokoll in zwei Stunden auseinandergenommen, und plötzlich ergab die Färbung …',
     'It was a full week, but the lab group carried me. Jana and Milan took the protocol apart in two hours, and suddenly the stain made sense …'],
    ['Stimmung 3', 'Mood 3'],
    ['Energie 2', 'Energy 2'],
    ['Wohnheim', 'Dorm'],
    ['11. Nov. nachtragen', 'Add 11 Nov'],
    ['noch kein Eintrag', 'no entry yet'],
    ['Montag · 19:35', 'Monday · 19:35'],
    ['aus „Laborjournal"', 'from “Lab Journal”'],
    ['aus „Laborjournal“', 'from “Lab Journal”'],
    ['Zellkultur angesetzt', 'Set up the cell culture'],
    ['Erste eigene Passage. Ich habe für das Zählen dreimal so lange gebraucht wie Milan und trotzdem war es der beste Nachmittag seit Semesterbeginn.',
     'First passage on my own. Counting took me three times as long as Milan and it was still the best afternoon since term started.'],
    ['Stimmung 5', 'Mood 5'],
    ['Energie 4', 'Energy 4'],
    ['Ältere Einträge · Oktober', 'Older entries · October'],
    ['SCHREIB-SERIE', 'WRITING STREAK'],
    ['Rekord 34', 'best 34'],
    ['12 Wochen · Lücke = nichts geschrieben · Ring = diese',
     '12 weeks · gap = nothing written · ring = this one'],
    ['November', 'November'],
    ['gefüllt = Eintrag · hohl = noch keiner', 'filled = entry · hollow = none yet'],
    ['Einträge dieser Woche', 'entries this week'],
    ['Aufgabe · offen', 'Task · open'],
    ['Passage 3', 'Passage 3'],
    ['Notiz · 12. Nov.', 'Note · 12 Nov'],
    ['Notiz · 12. Nov', 'Note · 12 Nov'],
    ['IMPULS FÜR HEUTE', 'PROMPT FOR TODAY'],
    ['Über den Versuch vom', 'Nothing has been written about the experiment on'],
    ['6. November', '6 November'],
    ['steht noch nichts.', 'yet.'],
    ['Messreihe Probe 1–5', 'Measurement series, samples 1–5'],

    /* ── Journal-Eintrag ──────────────────────────────────────────── */
    ['JOURNAL', 'JOURNAL'],
    ['EINTRAG 34 VON 41', 'ENTRY 34 OF 41'],
    ['Mittwoch, 12. November', 'Wednesday, 12 November'],
    ['Laborgruppe hat es endlich verstanden', 'The lab group finally got it'],
    ['Die Woche war voll, aber heute hat die Laborgruppe mich getragen — Jana und Milan haben das Protokoll auseinandergenommen.',
     'It was a full week, but today the lab group carried me — Jana and Milan took the protocol apart.'],
    ['Kurz vor fünf erklärte ich die Färbung noch einmal von vorn, und Jana hat den Satz vor mir zu Ende gebracht. Milan malte die Skizze frei an die Tafel.',
     'Just before five I explained the stain from the beginning again, and Jana finished the sentence before I could. Milan drew the sketch on the board from memory.'],
    ['Prof. Wendt kam vorbei und korrigierte nichts. Auf dem Rückweg über den Campus war ich zum ersten Mal seit September ruhig.',
     'Prof. Wendt came by and corrected nothing. Walking back across campus I was calm for the first time since September.'],
    ['DREI FOTOS · 21:48', 'THREE PHOTOS · 21:48'],
    ['Automatisch zugeordnet', 'Matched automatically'],
    ['Färbung, dritter Versuch', 'Stain, third attempt'],
    ['TON', 'AUDIO'],
    ['· eine Spur, zwei Marken', '· one track, two marks'],
    ['1:36 aufgenommen', '1:36 recorded'],
    ['Sprachnotiz ·', 'Voice note ·'],
    ['Nachtrag · nimmt auf ·', 'Addendum · recording ·'],
    ['VERBUNDEN', 'CONNECTED'],
    ['ENTSTANDEN AUS', 'GREW OUT OF'],
    ['DIESER EINTRAG', 'THIS ENTRY'],
    ['12. November', '12 November'],
    ['Journal · 22:10', 'Journal · 22:10'],
    ['DARAUS WURDE', 'WHAT IT BECAME'],
    ['STIMMUNG', 'MOOD'],
    ['3 von 5', '3 of 5'],
    ['Ausgeglichen', 'Even'],
    ['gewählt', 'selected'],
    ['ENERGIE', 'ENERGY'],
    ['4 von 5', '4 of 5'],
    ['ORT UND WETTER', 'PLACE AND WEATHER'],
    ['automatisch', 'automatic'],
    ['Universität, Gebäude B', 'University, building B'],
    ['Praktikumslabor 2', 'Teaching lab 2'],
    ['8 °C, bedeckt', '8 °C, overcast'],
    ['KATEGORIEN', 'CATEGORIES'],
    ['TAGS', 'TAGS'],
    ['Erstellt', 'Created'],
    ['Mi, 12. Nov · 22:10', 'Wed 12 Nov · 22:10'],
    ['heute · 9:28', 'today · 9:28'],
    ['In iCloud gesichert', 'Saved to iCloud'],

    /* ── Lernsitzung ──────────────────────────────────────────────── */
    ['von 23', 'of 23'],
    ['Karten in dieser Sitzung', 'cards in this session'],
    ['noch ca. 8 Minuten', 'about 8 minutes left'],
    ['Lernkarte · Deck „Zellbiologie"', 'Flashcard · “Cell Biology” deck'],
    ['Lernkarte · Deck „Zellbiologie“', 'Flashcard · “Cell Biology” deck'],
    ['zuletzt vor 8 Tagen · 4 × wiederholt', 'last seen 8 days ago · reviewed 4 ×'],
    ['Welche Funktion hat das Endoplasmatische Retikulum?',
     'What does the endoplasmic reticulum do?'],
    ['Antwort zeigen', 'Show answer'],
    ['SO STAND ES IN DEINER NOTIZ', 'HOW YOUR NOTE PUT IT'],
    ['„Das ER ist das größte Membransystem der Zelle — raues ER mit Ribosomen für die Faltung, glattes ER für Lipide und den Calcium-Speicher."',
     '“The ER is the cell’s largest membrane system — rough ER with ribosomes for folding, smooth ER for lipids and calcium storage.”'],
    ['„Das ER ist das größte Membransystem der Zelle — raues ER mit Ribosomen für die Faltung, glattes ER für Lipide und den Calcium-Speicher.“',
     '“The ER is the cell’s largest membrane system — rough ER with ribosomes for folding, smooth ER for lipids and calcium storage.”'],
    ['ANTWORT', 'ANSWER'],
    ['Das raue ER trägt Ribosomen auf seiner Membran und faltet die dort entstehenden Proteine, bevor sie zum Golgi-Apparat weiterwandern. Das glatte ER hat keine Ribosomen: es baut Lipide auf und hält den Calcium-Vorrat der Zelle bereit.',
     'Rough ER carries ribosomes on its membrane and folds the proteins made there before they travel on to the Golgi apparatus. Smooth ER has no ribosomes: it builds lipids and keeps the cell’s calcium supply ready.'],
    ['läuft ·', 'running ·'],
    ['Zur Stelle in der Notiz', 'Jump to it in the note'],
    ['Frage', 'Question'],
    ['Bildkarte', 'Image card'],
    ['Lichtmikroskop · Hämatoxylin-Eosin · 400 ×', 'Light microscope · haematoxylin-eosin · 400 ×'],
    ['Lernkarte · Deck „Mikroskopie"', 'Flashcard · “Microscopy” deck'],
    ['Lernkarte · Deck „Mikroskopie“', 'Flashcard · “Microscopy” deck'],
    ['Karte 8 von 23 · neu', 'Card 8 of 23 · new'],
    ['Welche Struktur ist hier dunkelviolett angefärbt — und woran erkennst du sie?',
     'Which structure is stained dark violet here — and how do you recognise it?'],
    ['aus „Mikroskopie"', 'from “Microscopy”'],
    ['aus „Mikroskopie“', 'from “Microscopy”'],
    ['WIEDERHOLUNGEN DIESER KARTE', 'THIS CARD’S REVIEWS'],
    ['gefüllt = gelaufen · Ring = jetzt fällig · hohl = geplant',
     'filled = done · ring = due now · hollow = planned'],
    ['gleich', 'now'],
    ['Tastatur: Leertaste dreht um · 1 – 4 bewerten',
     'Keyboard: space flips · 1 – 4 to grade'],
    ['Nochmal', 'Again'],
    ['gleich wieder', 'right away'],
    ['Schwer', 'Hard'],
    ['bleibt bei 8 Tagen', 'stays at 8 days'],
    ['Gut', 'Good'],
    ['in 21 Tagen', 'in 21 days'],
    ['Leicht', 'Easy'],
    ['in 55 Tagen', 'in 55 days'],
    ['Bis morgen zurücklegen', 'Put off until tomorrow'],
    ['Aussetzen', 'Suspend'],
    ['Bearbeiten', 'Edit'],
    ['Gesichert', 'Saved'],
    ['MITRECHNEN', 'SCRATCHPAD'],
    ['bleibt an der Karte', 'stays with the card'],
    ['Stift', 'Pen'],
    ['Radierer', 'Eraser'],
    ['Lineal', 'Ruler'],
    ['Leeren', 'Clear'],
    ['DIESE SITZUNG', 'THIS SESSION'],
    ['im Nochmal-Stapel', 'in the again pile'],
    ['kommen wieder', 'coming back'],
    ['Deck „Anatomie Grundlagen"', '“Anatomy Basics” deck'],
    ['Deck „Anatomie Grundlagen“', '“Anatomy Basics” deck'],
    ['ZULETZT BEWERTET', 'LAST GRADED'],
    ['Zurücknehmen', 'Undo'],
    ['in 5 Tagen', 'in 5 days'],
    ['in 12 Tagen', 'in 12 days'],

    /* ── Lernkarten (Übersicht) ───────────────────────────────────── */
    ['Alle lernen', 'Study all'],
    ['Donnerstag, 13. November —', 'Thursday, 13 November —'],
    ['23 Karten', '23 cards'],
    ['fällig: 8 neue, 15 Wiederholungen, rund 11 Minuten.',
     'due: 8 new, 15 reviews, about 11 minutes.'],
    ['DECKS', 'DECKS'],
    ['Fällig zuerst', 'Due first'],
    ['A–Z', 'A–Z'],
    ['Wiederholen', 'Review'],
    ['Gelernt', 'Learned'],
    ['8 fällig', '8 due'],
    ['4 von 12 sitzen', '4 of 12 solid'],
    ['NÄCHSTE KARTEN', 'NEXT CARDS'],
    ['Rückseite verdeckt', 'back hidden'],
    ['Aufgabe der inneren Membran?', 'What does the inner membrane do?'],
    ['Was passiert im cis-Netz?', 'What happens in the cis-network?'],
    ['Anatomie Grundlagen', 'Anatomy Basics'],
    ['aus 3 Notizen', 'from 3 notes'],
    ['wöchentlich', 'weekly'],
    ['52 von 64 sitzen', '52 of 64 solid'],
    ['12 fällig', '12 due'],
    ['Statistik-Formeln', 'Statistics Formulas'],
    ['aus „Formelsammlung"', 'from “Formula Sheet”'],
    ['aus „Formelsammlung“', 'from “Formula Sheet”'],
    ['28 von 31 sitzen', '28 of 31 solid'],
    ['3 fällig', '3 due'],
    ['aus „Weber"', 'from “Weber”'],
    ['aus „Weber“', 'from “Weber”'],
    ['Noch keine Karten', 'No cards yet'],
    ['0 Karten — in „Weber, Kap. 3" sind drei Stellen markiert.',
     '0 cards — three passages are marked in “Weber, ch. 3”.'],
    ['0 Karten — in „Weber, Kap. 3“ sind drei Stellen markiert.',
     '0 cards — three passages are marked in “Weber, ch. 3”.'],
    ['Notiz öffnen', 'Open note'],
    ['ERTRAG · 12 WOCHEN', 'YIELD · 12 WEEKS'],
    ['48 Tage', '48 days'],
    ['Sep', 'Sep'],
    ['Okt', 'Oct'],
    ['Nov', 'Nov'],
    ['Eine Zelle ist ein Tag. Dichte = wie viel vom Material dieses Tages heute sitzt.',
     'One cell is one day. Density = how much of that day’s material is solid now.'],
    ['von 107 sitzen', 'of 107 solid'],
    ['zu jung', 'too new'],
    ['nichts', 'none'],
    ['alles', 'all'],
    ['längste 34', 'best 34'],
    ['ZIEL-ERINNERUNGSRATE', 'TARGET RECALL'],
    ['70 bis 97 %. Bei 90 % rund 17 Karten am Tag, bei 85 % nur 12.',
     '70 to 97 %. At 90 % about 17 cards a day, at 85 % only 12.'],
    ['ABSTÄNDE · „OSMOSE"', 'INTERVALS · “OSMOSIS”'],
    ['ABSTÄNDE · „OSMOSE“', 'INTERVALS · “OSMOSIS”'],
    ['Dreimal richtig hintereinander — die gefüllten Punkte liegen hinter der Karte, die hohlen vor ihr.',
     'Three right in a row — filled dots are behind the card, hollow ones ahead of it.'],
    ['PROGNOSE · 7 TAGE', '7-DAY FORECAST'],
    ['Morgen', 'Tomorrow'],
    ['ca. 17', 'about 17'],
    ['DIE QUELLE DIESER 12 KARTEN', 'WHERE THESE 12 CARDS CAME FROM'],
    ['14 Absätze · 9 markiert · gestern 16:20', '14 paragraphs · 9 marked · yesterday 16:20'],
    ['„Osmose ist die Diffusion von Wasser durch eine selektiv permeable Membran."',
     '“Osmosis is the diffusion of water through a selectively permeable membrane.”'],
    ['„Osmose ist die Diffusion von Wasser durch eine selektiv permeable Membran.“',
     '“Osmosis is the diffusion of water through a selectively permeable membrane.”'],
    ['Aus diesem Absatz sind 2 Karten geworden.', 'Two cards came out of this paragraph.'],
    ['Loslassen', 'Release'],

    ['2 von 4', '2 of 4'],
    ['1 von 2', '1 of 2'],
    ['0 von 2', '0 of 2'],
    ['Sprachnotiz · abgetippt', 'Voice note · transcribed'],
    ['Schritt gesichert', 'Step saved'],
    ['Nachtrag ·', 'Addendum ·'],
    ['Zellbiologie — Vorlesung 6', 'Cell Biology — Lecture 6'],
    ['31 Seiten', '31 pages'],
    ['Whiteboard', 'Cell Biology — Lecture 9'],

    /* ── Was die Erfassungszeile beim Tippen baut (§12e) ──────────── */
    ['Morgen · 14:00', 'Tomorrow · 14:00'],
    ['Heute · 14:00', 'Today · 14:00'],
    ['Morgen', 'Tomorrow'],
    ['Markiert', 'Flagged'],
    ['Mittlere Priorität', 'Medium priority'],
    ['Nur ein Titel', 'Just a title'],
    ['Landet in der Gruppe Biologie', 'Files under Biology'],
    ['Landet unter „Morgen"', 'Files under Tomorrow'],
    ['Landet unter „Morgen“', 'Files under Tomorrow'],
    ['Landet im Eingang — ohne Gruppe, ohne Termin', 'Goes to the inbox — no group, no date'],
    ['Aufgabe in einem Satz erfassen', 'Capture a task in one sentence'],

    /* ── Was die Umschalter zur Laufzeit bauen (§14c) ─────────────── */
    ['HEUTE', 'TODAY'],
    ['MORGEN', 'TOMORROW'],
    ['DIESE WOCHE', 'THIS WEEK'],
    ['OHNE TERMIN', 'UNSCHEDULED'],
    ['OFFEN', 'OPEN'],
    ['IN ARBEIT', 'IN PROGRESS'],
    ['ERLEDIGT', 'DONE'],
    ['was heute drankommt', 'what is up today'],
    ['schon terminiert', 'already scheduled'],
    ['mit Frist, ohne Tag', 'has a deadline, no day'],
    ['wartet auf eine Entscheidung', 'waiting on a decision'],
    ['noch nicht angefangen', 'not started'],
    ['begonnen', 'started'],
    ['heute abgehakt', 'ticked off today'],
    ['nichts', 'nothing'],
    ['Dringend · wichtig', 'Urgent · important'],
    ['Wichtig · nicht dringend', 'Important · not urgent'],
    ['Dringend · unwichtig', 'Urgent · not important'],
    ['Keins von beidem', 'Neither'],
    ['zuerst', 'first'],
    ['planen', 'plan it'],
    ['abgeben', 'hand it off'],
    ['irgendwann', 'someday'],

    /* ── Canvas ───────────────────────────────────────────────────── */
    ['Zurück zu Velum', 'Back to Velum'],

    /* ── Graph, Suche, Semester, Einstellungen: nur was im Bild
          auftauchen kann, wenn ein Schirm kurz vorbeizieht ────────── */
    ['Graph', 'Graph'],
    ['Journal', 'Journal'],
    ['Canvas', 'Canvas'],
    ['Sichern und schließen', 'Save and close'],
    ['Schließen', 'Close'],
    ['Abbrechen', 'Cancel'],
    ['Fertig', 'Done'],
    ['Zurück', 'Back'],
    ['Mehr', 'More'],
    ['Sortieren', 'Sort'],
    ['Filter', 'Filter'],
    ['Anheften', 'Pin'],
    ['Export', 'Export'],
  ];

  /* Wörter, die auch in Attributen vorkommen: aria-label, placeholder, title.
     Dieselbe Tabelle, nur ein anderer Träger. */
  var ATTRIBUTE = ['aria-label', 'placeholder', 'title', 'alt', 'data-pv-name'];

  function normal(s) {
    return String(s)
      .replace(/[­​‌‍﻿]/g, '')   /* Trennhilfen */
      .replace(/ /g, ' ')                             /* geschütztes Leerz. */
      .replace(/\s+/g, ' ')
      .trim();
  }

  var WOERTER = Object.create(null);
  PAARE.forEach(function (p) { WOERTER[normal(p[0])] = p[1]; });

  /* Erkennt Reste: Umlaut, ß, oder ein deutsches Funktionswort. Zahlen,
     Namen und Fachbegriffe fallen nicht darunter — die sollen bleiben. */
  /* „was", „man", „die", „am", „im", „so" sind auch englische Wörter — stünden
     sie hier, meldete der Test jeden zweiten englischen Satz als deutschen. */
  var STOPP = new RegExp('(^|\\s)(der|den|dem|des|das|und|oder|für|von|mit|auf|aus|zur|zum|' +
    'ist|sind|war|wird|werden|nicht|ohne|noch|schon|dass|wie|wer|wenn|aber|auch|' +
    'eine|einen|einem|eines|kein|keine|sich|seit|nach|über|unter|vor|beim|' +
    'durch|zwischen|gegen|jede|jeder|alle|mehr|sehr|hier|dann|damit|weil|wurde|haben|hat)(\\s|$)', 'i');

  function deutschVerdacht(s) {
    var t = normal(s);
    if (!t || t.length < 3) return false;
    if (/^[\d\s.,:;·/%°+×–—-]+$/.test(t)) return false;     /* reine Zahlen/Zeichen */
    return /[äöüÄÖÜß]/.test(t) || STOPP.test(t);
  }

  function textKnoten(wurzel, treffer, rest) {
    var lauf = document.createTreeWalker(wurzel, NodeFilter.SHOW_TEXT);
    var n, arbeit = [];
    while ((n = lauf.nextNode())) arbeit.push(n);
    arbeit.forEach(function (k) {
      var roh = k.textContent;
      if (!roh || !roh.trim()) return;
      var schl = normal(roh);
      if (Object.prototype.hasOwnProperty.call(WOERTER, schl)) {
        /* Randleerzeichen erhalten: „aus " + Name ist zwei Knoten. */
        var vorn = roh.match(/^\s*/)[0];
        var hinten = roh.match(/\s*$/)[0];
        k.textContent = vorn + WOERTER[schl] + hinten;
        treffer.push(schl);
      } else if (deutschVerdacht(schl)) {
        rest.push(schl);
      }
    });
  }

  function attribute(wurzel, treffer, rest) {
    var alle = [wurzel].concat([].slice.call(wurzel.querySelectorAll('*')));
    alle.forEach(function (el) {
      ATTRIBUTE.forEach(function (a) {
        if (!el.getAttribute) return;
        var v = el.getAttribute(a);
        if (!v) return;
        var schl = normal(v);
        if (Object.prototype.hasOwnProperty.call(WOERTER, schl)) {
          el.setAttribute(a, WOERTER[schl]);
          treffer.push(schl);
        } else if (deutschVerdacht(schl)) {
          rest.push('[' + a + '] ' + schl);
        }
      });
    });
  }

  /* Auf alles anwenden, was gerade im Dokument steht — auch auf verborgene
     Schirme, denn sie werden während der Aufnahme sichtbar. */
  function umstellen(wurzel) {
    var treffer = [], rest = [];
    var w = wurzel || document.body;
    textKnoten(w, treffer, rest);
    attribute(w, treffer, rest);
    return { getroffen: treffer.length, rest: rest };
  }

  global.ENGLISCH = {
    umstellen: umstellen,
    woerter: WOERTER,
    normal: normal,
    verdacht: deutschVerdacht,
    /* Nach jeder Bedienung erneut laufen lassen: der Prototyp baut Karten,
       Zeilen und Tafeln zur Laufzeit nach (§12 – §14). */
    nachziehen: function () { return umstellen(document.body); },
  };
})(window);
